/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TotalMsgImport } from './routes/totalMsg'
import { Route as MessagesImport } from './routes/messages'
import { Route as CreateMessageImport } from './routes/createMessage'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const TotalMsgRoute = TotalMsgImport.update({
  id: '/totalMsg',
  path: '/totalMsg',
  getParentRoute: () => rootRoute,
} as any)

const MessagesRoute = MessagesImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRoute,
} as any)

const CreateMessageRoute = CreateMessageImport.update({
  id: '/createMessage',
  path: '/createMessage',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/createMessage': {
      id: '/createMessage'
      path: '/createMessage'
      fullPath: '/createMessage'
      preLoaderRoute: typeof CreateMessageImport
      parentRoute: typeof rootRoute
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesImport
      parentRoute: typeof rootRoute
    }
    '/totalMsg': {
      id: '/totalMsg'
      path: '/totalMsg'
      fullPath: '/totalMsg'
      preLoaderRoute: typeof TotalMsgImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/createMessage': typeof CreateMessageRoute
  '/messages': typeof MessagesRoute
  '/totalMsg': typeof TotalMsgRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/createMessage': typeof CreateMessageRoute
  '/messages': typeof MessagesRoute
  '/totalMsg': typeof TotalMsgRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/createMessage': typeof CreateMessageRoute
  '/messages': typeof MessagesRoute
  '/totalMsg': typeof TotalMsgRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/createMessage' | '/messages' | '/totalMsg'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/createMessage' | '/messages' | '/totalMsg'
  id: '__root__' | '/' | '/about' | '/createMessage' | '/messages' | '/totalMsg'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CreateMessageRoute: typeof CreateMessageRoute
  MessagesRoute: typeof MessagesRoute
  TotalMsgRoute: typeof TotalMsgRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CreateMessageRoute: CreateMessageRoute,
  MessagesRoute: MessagesRoute,
  TotalMsgRoute: TotalMsgRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/createMessage",
        "/messages",
        "/totalMsg"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/createMessage": {
      "filePath": "createMessage.tsx"
    },
    "/messages": {
      "filePath": "messages.tsx"
    },
    "/totalMsg": {
      "filePath": "totalMsg.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
