/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedTotalMsgImport } from './routes/_authenticated/totalMsg'
import { Route as AuthenticatedProfileImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMessagestestImport } from './routes/_authenticated/messagestest'
import { Route as AuthenticatedMessagesImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedCreateMessageImport } from './routes/_authenticated/createMessage'
import { Route as AuthenticatedMessageIdEditImport } from './routes/_authenticated/message.$id.edit'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedTotalMsgRoute = AuthenticatedTotalMsgImport.update({
  id: '/totalMsg',
  path: '/totalMsg',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedProfileRoute = AuthenticatedProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMessagestestRoute = AuthenticatedMessagestestImport.update({
  id: '/messagestest',
  path: '/messagestest',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedMessagesRoute = AuthenticatedMessagesImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedCreateMessageRoute = AuthenticatedCreateMessageImport.update(
  {
    id: '/createMessage',
    path: '/createMessage',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

const AuthenticatedMessageIdEditRoute = AuthenticatedMessageIdEditImport.update(
  {
    id: '/message/$id/edit',
    path: '/message/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/createMessage': {
      id: '/_authenticated/createMessage'
      path: '/createMessage'
      fullPath: '/createMessage'
      preLoaderRoute: typeof AuthenticatedCreateMessageImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/messagestest': {
      id: '/_authenticated/messagestest'
      path: '/messagestest'
      fullPath: '/messagestest'
      preLoaderRoute: typeof AuthenticatedMessagestestImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/totalMsg': {
      id: '/_authenticated/totalMsg'
      path: '/totalMsg'
      fullPath: '/totalMsg'
      preLoaderRoute: typeof AuthenticatedTotalMsgImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/message/$id/edit': {
      id: '/_authenticated/message/$id/edit'
      path: '/message/$id/edit'
      fullPath: '/message/$id/edit'
      preLoaderRoute: typeof AuthenticatedMessageIdEditImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedCreateMessageRoute: typeof AuthenticatedCreateMessageRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMessagestestRoute: typeof AuthenticatedMessagestestRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTotalMsgRoute: typeof AuthenticatedTotalMsgRoute
  AuthenticatedMessageIdEditRoute: typeof AuthenticatedMessageIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCreateMessageRoute: AuthenticatedCreateMessageRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMessagestestRoute: AuthenticatedMessagestestRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTotalMsgRoute: AuthenticatedTotalMsgRoute,
  AuthenticatedMessageIdEditRoute: AuthenticatedMessageIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/createMessage': typeof AuthenticatedCreateMessageRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/messagestest': typeof AuthenticatedMessagestestRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/totalMsg': typeof AuthenticatedTotalMsgRoute
  '/message/$id/edit': typeof AuthenticatedMessageIdEditRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/createMessage': typeof AuthenticatedCreateMessageRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/messagestest': typeof AuthenticatedMessagestestRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/totalMsg': typeof AuthenticatedTotalMsgRoute
  '/message/$id/edit': typeof AuthenticatedMessageIdEditRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/_authenticated/createMessage': typeof AuthenticatedCreateMessageRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/messagestest': typeof AuthenticatedMessagestestRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/totalMsg': typeof AuthenticatedTotalMsgRoute
  '/_authenticated/message/$id/edit': typeof AuthenticatedMessageIdEditRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/about'
    | '/createMessage'
    | '/messages'
    | '/messagestest'
    | '/profile'
    | '/totalMsg'
    | '/message/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/about'
    | '/createMessage'
    | '/messages'
    | '/messagestest'
    | '/profile'
    | '/totalMsg'
    | '/message/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/_authenticated/createMessage'
    | '/_authenticated/messages'
    | '/_authenticated/messagestest'
    | '/_authenticated/profile'
    | '/_authenticated/totalMsg'
    | '/_authenticated/message/$id/edit'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/createMessage",
        "/_authenticated/messages",
        "/_authenticated/messagestest",
        "/_authenticated/profile",
        "/_authenticated/totalMsg",
        "/_authenticated/message/$id/edit"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authenticated/createMessage": {
      "filePath": "_authenticated/createMessage.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/messages": {
      "filePath": "_authenticated/messages.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/messagestest": {
      "filePath": "_authenticated/messagestest.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/profile": {
      "filePath": "_authenticated/profile.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/totalMsg": {
      "filePath": "_authenticated/totalMsg.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/message/$id/edit": {
      "filePath": "_authenticated/message.$id.edit.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
